---
### Use this file to format new server, update, upgrade and harden security ###

- name: Install Cardono Node
  hosts: cardano
  user: root

  tasks:

  - name: Update apt repo, cache, upgrade and enable unattended upgrades
    apt: 
      update_cache: yes
      force_apt_get: yes 
      cache_valid_time: 3600
      upgrade: yes

  - name: Install required packages
    apt:
      pkg:
        - git
        - automake 
        - build-essential 
        - pkg-config 
        - libffi-dev 
        - libgmp-dev 
        - libssl-dev 
        - libtinfo-dev 
        - libsystemd-dev 
        - zlib1g-dev 
        - make 
        - g++ 
        - tmux
        - jq 
        - wget 
        - libncursesw5 
        - libtool 
        - autoconf
        - net-tools
        - chrony
      state: present

  - name: Create 'wheel' group
    group: 
      name: wheel
      state: present

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Add Cardano user
    ansible.builtin.user:
      name: cardano
      state: present
      groups: wheel
      shell: /bin/bash
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - name: Enable UFW and allow logging
    ufw:
      state: enabled
      logging: on

  - name: Disable ports 300, 9100, 12798
    ufw:    
      rule: deny
      proto: tcp
      #direction: incoming
      port: '{{ item }}'
    with_items:
      - 3000
      - 9100
      - 12798

  - name: Allow port 22 and 6000
    ufw:
      proto: tcp
      rule: allow
      port: '{{ item }}'
    with_items:
      - 22
      - 6000
  
  - name: verify listening ports
    shell: /bin/netstat -tulpn
    register: 
      netstat_result

  - name: List TCP/UDP ports listenting
    debug:
      msg: "For ports: {{ netstat_result.stdout }}"
 

  # - name: Deny all IPv6 traffic
  #   ufw:
  #     proto: ipv6
  #     rule: deny










