---

- name: Install Cardono Node
  hosts: cardano
  user: root

  tasks:

  - name: Update apt-get repo and cache
    apt: 
      update_cache: yes
      force_apt_get: yes 
      cache_valid_time: 3600

  - name: Install required packages
    apt:
      pkg:
        - git
        - automake 
        - build-essential 
        - pkg-config 
        - libffi-dev 
        - libgmp-dev 
        - libssl-dev 
        - libtinfo-dev 
        - libsystemd-dev 
        - zlib1g-dev 
        - make 
        - g++ 
        - tmux
        - jq 
        - wget 
        - libncursesw5 
        - libtool 
        - autoconf
      state: present










